#demo.yaml

apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  labels:
    app: demo
  name: demo
  namespace: nju30
spec:
  replicas: 1  #运行容器的副本数
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: demo
    spec:
      containers: #docker容器的配置
        - image: harbor.edu.cn/nju30/demo:{VERSION} #pull镜像的地址
          name: demo
      imagePullSecrets:
        - name: nju30-secret
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: nju30
  labels:
    app: demo
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - name: tcp
      nodePort: 31105  #host's port
      protocol: TCP
      port: 8080  #service's port
      targetPort: 8080  #target pod's port
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: demo
  name: demo
  namespace: nju30
spec:
  endpoints:
    - interval: 30s
      port: tcp
      path: /actuator/prometheus
      scheme: 'http'
  selector:
    matchLabels:
      app: demo
  namespaceSelector:
    matchNames:
      - nju30
